id: cdde3a4b-9eb1-42bd-ada4-1739cefbfed9
type: multiple_choice
version: 1.0.0.0
title: cap of ny
domain: geo
tags:
  - geo
  - multiple_choice
created_at: '2026-03-05T10:30:18.577Z'
modified_at: '2026-03-05T10:30:18.577Z'
